### ISSUE TITLE
TypeError: int() argument must be a string

### ISSUE THREAD

**Issue by marssystems** [jcomeauictx/slotmachine#3]
I'm getting this error when I run the program.

Windows 11 64 bit - Python 3.10.4

D:\slotmachine>python slotmachine.py
Traceback (most recent call last):
  File "D:\slotmachine\slotmachine.py", line 28, in <module>
    MAX_ADDRESSES = int(os.getenv('MAX_ADDRESSES')) or 4000000
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by jcomeauictx** [comment]
`git pull` and try now.

**Comment by marssystems** [comment]
Yes - that's fixed it - thanks!

**Comment by jcomeauictx** [comment]
Great! Thanks for the bug report.

**Comment by marssystems** [comment]
No worries - my pleasure.
